// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjBNEfmxa8h9-EGMoMa7KL4I6JO7YckiA',
    appId: '1:310241759905:android:c11cb40d648c24bf98d6e0',
    messagingSenderId: '310241759905',
    projectId: 'chatty-77161',
    storageBucket: 'chatty-77161.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcMqQihqWzDcdf3DV9LlAUVNF6-HcyzIo',
    appId: '1:310241759905:ios:f057cdd08fc31a6a98d6e0',
    messagingSenderId: '310241759905',
    projectId: 'chatty-77161',
    storageBucket: 'chatty-77161.appspot.com',
    androidClientId: '310241759905-8hb732g2h5ak5nl9gn2kmpj5ndg42bho.apps.googleusercontent.com',
    iosClientId: '310241759905-jjlk85j2evpug9ulfvjmg5rv3026fs1m.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
